@startuml sequence_diagram

title Secuencia - Subida de PDF

actor Usuario

participant FastAPI
participant PDFService
participant ChecksumService
participant AIService
participant Repository
database MongoDB

Usuario -> FastAPI : POST /upload-pdf

FastAPI -> PDFService : extract_text(pdf)
PDFService --> FastAPI : texto extraído

FastAPI -> ChecksumService : calcular_checksum(pdf)
ChecksumService --> FastAPI : checksum

FastAPI -> AIService : summarize_text(texto)
AIService --> FastAPI : resumen generado

FastAPI -> Repository : guardar_documento()

Repository -> MongoDB : insertOne()

MongoDB --> Repository : OK

Repository --> FastAPI : documento guardado

FastAPI --> Usuario : Response 200

@enduml